# playbook.yml
---
- hosts: localhost
  connection: local
  tasks:
    - name: cleanup dangling images
      shell: |
        oldimage=`docker images | grep '<none>' | awk '{print $3}'`
        if [ -z "$oldimage" ]
        then
        echo "There is no dangling images found!"
        else
        docker rmi ${oldimage} -f
        fi
        
      ignore_errors: yes
      become: true
      
    - name: Run Docker container using dockerhub
      docker_container:
        name: TestApp
        image: "yagnya42/testapp:{{dockertag}}"
        state: started
        recreate: yes
        detach: true
        pull: yes
        ports:
          - "9091:8080"
