# playbook.yml
---
- hosts: localhost
  connection: local
  tasks:
    - name: Run Docker container using dockerhub
      docker_container:
        name: TestApp
        image: yagnya42/testapp:${DOCKER_TAG}
        state: started
        recreate: yes
        detach: true
        pull: yes
        ports:
          - "9091:8080"
