---
#Simple Ansible Playbook to build and push Docker image to Registry
 
- name: Playbook to build and run Docker
  hosts: localhost
  connection: local
  gather_facts: false
 
  tasks:
     - name: Install docker-py python module
       pip:
        name: docker-py
        state: present
        
     - name: Run Docker container using dockerhub
       docker_container:
        name: TestApp
        image: yagnya42/testapp:b751740
        state: started
        recreate: yes
        detach: true
        pull: yes
        ports:
          - "9091:8080"
