# playbook.yml
---
- hosts: localhost
  connection: local
  tasks:
    - name: Stop running containers
      docker_container:
        name: "{{ item }}"
        state: stopped
        loop: "{{ docker_info.containers | map(attribute='Id') | list }}"
        
    - name: Remove Stoped docker containers
      shell: |
         docker rm $(docker ps -a -q);
         when: docker_info.containers != 0
         
    - name: Get details of all images
      docker_host_info:
        images: yes
        verbose_output: yes
        register: image_info
        
    - name: Remove all images
      docker_image:
        name: "{{ item }}"
        state: absent
        loop: "{{ image_info.images | map(attribute='Id') | list }}"
      
    - name: Run Docker container using dockerhub
      docker_container:
        name: TestApp
        image: "yagnya42/testapp:{{dockertag}}"
        state: started
        recreate: yes
        detach: true
        pull: yes
        ports:
          - "9091:8080"
