# playbook.yml
---
- hosts: localhost
  connection: local
  tasks:
    - name: Remove image
      docker_image:
      state: absent
      name: yagnya42/testapp
      tag: *
      
    - name: Run Docker container using dockerhub
      docker_container:
        name: TestApp
        image: "yagnya42/testapp:{{dockertag}}"
        state: started
        recreate: yes
        detach: true
        pull: yes
        ports:
          - "9091:8080"
